import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DC app",
  description: "Generated by Tan Ton Ten",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
          {/* chỉnh sửa bg color theo theme  */}
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} storageKey="dc-theme">
            {children}
          </ThemeProvider>

        </body>
      </html>
    </ClerkProvider>
  );
}
